### ISSUE TITLE
Remove night vision when slinging the helmet

### ISSUE THREAD

**Issue by Synch2k** [gruppe-adler/grad_slingHelmet#16]
If you are slinging your helmet while using night vision goggles the goggles will stay on your head, which may end up looking ridiculous.

Maybe save whatever night vision goggles the user is wearing, remove it when slinging the helmet and reapply when unslinging the helmet?

**Comment by DerZade** [comment]
Interesting suggestion. So we should move from  `slingHelmet` to `slingNVGandHelmet`? :P  

I get your point, but this could complicate things. What it the user doesn't want to loose his NVGs when slinging the helmet? 
What happens if a player wants to unsling his helmet (which include NVGs), but wears new NVGs? Should the action be disabled in the first place like it is, when hes wearing a headgear? Should we just replace his NVGs with the ones he slung?

Any suggestions?

**Comment by Synch2k** [comment]
Edge cases.. love it :) So personally I would like to think of helmet and NVG as one unit - as one is mounted to the other:
> What it the user doesn't want to loose his NVGs when slinging the helmet?  

Then he should unmount it from the helmet - no mod support needed, just use the vanilla inventory system.  
> What happens if a player wants to unsling his helmet (which include NVGs), but wears new NVGs?Should the action be disabled in the first place like it is, when hes wearing a headgear?

Yes, exactly. "You have NVGs strapped to your head you cannot just put your helmet on top of it" But I would suggest that you make it clear for the user why he cannot unsling his helmet - for both cases actually (helmet and nvg)

I think this would be an improvement to the current situation as you make the player aware of what exactly is happening. Unlike now where only one half of your headgear is removed which leaves users with floating NVGs over there head (unless the NVGs are vanilla and get a magical headstrap after you remove the helmet)  without them directly realising it

**Comment by DerZade** [comment]
I'll talk with the rest of the team about it. 😉

**Comment by DerZade** [comment]
Sorry, but we decided not to implement something like this, because it would - like I already explained above - introduce a lot of challenges in terms of usability.
