### ISSUE TITLE
Use a much better method of defining a classnames whitelist

### ISSUE THREAD

**Issue by Saborknight** [gruppe-adler/grad_slingHelmet#35]
So, in my work on the external intercom Dedmen gave me this little tidbit of knowledge that I think could be applied to the whitelisting in slingHelmet: https://github.com/michail-nikolaev/task-force-arma-3-radio/pull/1530#discussion_r670549067

Essentially, I recommend either creating a class with subclasses for each whitelisted helmet, or make a property to be defined for each whitelisted headgear.

Here's what I did for the external intercom was create a global class and just added subclasses for each whitelisted item: https://github.com/michail-nikolaev/task-force-arma-3-radio/pull/1530/files#diff-153feaa86d46c83d3f066dda91b76081f218a4cab04a43df9a9f6ba4f995620e

What this means is that you don't have to handle whitelisting anymore since any mod maker can make their own gear compatible without any of your intervention. Plus... it makes sense to take data out of SQF as much as possible.

You could argue that this is the same as the array that you define in slingHelmet, but it's much easier for a modmaker to add items to the class than it is to a global variable.

**Comment by Dahlgren** [comment]
Like the example in wiki? 🙂 

https://github.com/gruppe-adler/grad_slingHelmet/wiki/Adding-Headgear-to-the-Whitelist#adding-via-config-entry

**Comment by DerZade** [comment]
We’re not exactly doing what you did in TFAR, but adding to the whitelist via config entry is possible as Dahlgren pointed out. 
Just instead of having one whitelist global class with all helmets as subclasses, we use an attribute within the helmet’s `CfgWeapons` class. 

I still agree with your second thought. It would probably be cleaner to have the global whitelist as a config class instead of one big SQF array.
And It would make merging Whitelist-PRs easier, because you wouldn’t have to think about dangling commas, but at the same time it might overcomplicate things for people without much knowledge of Arma 3 modding. Explaining an array is a lot simpler, than config sub classes. 😅

I’ll think about it :)

**Comment by Saborknight** [comment]
I hadn't worked with slingHelmet for so long that I completely forgot those other methods were available. Hell, you even have a CBA setting for it so there actually isn't any change crucial. I just remember doing it the array away in the past which is why it's the only method I remember.

My bad!
